[2020-02-25 13:46:27,965] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: pouli.step__main_step__test__1 2020-02-25T13:43:07+00:00 [queued]>
[2020-02-25 13:46:28,008] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: pouli.step__main_step__test__1 2020-02-25T13:43:07+00:00 [queued]>
[2020-02-25 13:46:28,008] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-02-25 13:46:28,008] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2020-02-25 13:46:28,008] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-02-25 13:46:28,036] {taskinstance.py:887} INFO - Executing <Task(BashOperator): step__main_step__test__1> on 2020-02-25T13:43:07+00:00
[2020-02-25 13:46:28,041] {standard_task_runner.py:53} INFO - Started process 5340 to run task
[2020-02-25 13:46:28,178] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: pouli.step__main_step__test__1 2020-02-25T13:43:07+00:00 [running]> df49cf1bf754
[2020-02-25 13:46:28,262] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-02-25 13:46:28,265] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmpa2_qitve/step__main_step__test__1gdt23wdb
[2020-02-25 13:46:28,265] {bash_operator.py:115} INFO - Running command: 
OBC_START=$(eval "declare")
:
# Insert the BASH commands for this step.
# You can use the variable ${OBC_WORK_PATH} as your working directory.

touch /usr/local/airflow/WORK/aaa.bbb

echo "Hello"
OBC_CURRENT=$(eval "declare")
comm -3 <(echo "$OBC_START" | grep -v "_=") <(echo "$OBC_CURRENT" | grep -v OBC_START | grep -v PIPESTATUS | grep -v "_=") > ${OBC_WORK_PATH}/step__main_step__test__1__1.sh

[2020-02-25 13:46:28,291] {bash_operator.py:122} INFO - Output:
[2020-02-25 13:46:28,313] {bash_operator.py:126} INFO - touch: cannot touch '/usr/local/airflow/WORK/aaa.bbb': No such file or directory
[2020-02-25 13:46:28,316] {bash_operator.py:126} INFO - Hello
[2020-02-25 13:46:28,330] {bash_operator.py:126} INFO - /tmp/airflowtmpa2_qitve/step__main_step__test__1gdt23wdb: line 11: /usr/local/airflow/WORK/step__main_step__test__1__1.sh: No such file or directory
[2020-02-25 13:46:28,357] {bash_operator.py:130} INFO - Command exited with return code 1
[2020-02-25 13:46:28,397] {taskinstance.py:1128} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-02-25 13:46:28,408] {taskinstance.py:1185} INFO - Marking task as FAILED.dag_id=pouli, task_id=step__main_step__test__1, execution_date=20200225T134307, start_date=20200225T134627, end_date=20200225T134628
[2020-02-25 13:46:37,920] {logging_mixin.py:112} INFO - [2020-02-25 13:46:37,918] {local_task_job.py:103} INFO - Task exited with return code 1
